sudo: required
services:
  - docker

before_install:
  - docker build -t akinfergie/docker-react -f Dockerfile.dev .

script:
  - docker run akinfergie/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id:
  secret_access_key:
    secure: ""
